(function(){
  function qs(s,r){return (r||document).querySelector(s)}
  function qsa(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s))}
  function isTool(){return location.pathname.indexOf('/tools/')>-1}
  function isBlog(){return location.pathname.indexOf('/blog/')>-1}
  function rel(path){return isTool()||isBlog()?'../'+path:path}
  function pageTitle(){var h=qs('h1');return (h?h.textContent:document.title).replace(/\s+/g,' ').replace(/\s*\|\s*ToolNest Studio$/,'').trim()||'ToolNest Studio'}
  function styles(){if(qs('#tn-fixes'))return;var s=document.createElement('style');s.id='tn-fixes';s.textContent='.tn-guide{max-width:1120px;margin:0 auto 4rem;padding:0 1.5rem}.tn-guide-box{background:var(--s);border:1px solid var(--b);border-radius:24px;padding:1.6rem}.tn-guide p,.tn-guide li{color:var(--t2);line-height:1.75;font-size:.92rem}.tn-guide-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:1rem}.tn-guide-card{border:1px solid var(--b);border-radius:18px;padding:1rem;background:rgba(255,255,255,.03)}.tn-policy-links{display:flex;gap:.75rem;flex-wrap:wrap;margin-top:.85rem}.tn-policy-links a{color:var(--t3);font-size:.8rem;text-decoration:none}';document.head.appendChild(s)}
  function textFixes(){qsa('body *').forEach(function(el){if(el.childElementCount===0&&el.textContent){el.textContent=el.textContent.replace(/Published by ToolNest Studio/g,'Written By ToolNest Studio Team').replace(/Published by ToolNest Studio ·/g,'Written By ToolNest Studio Team ·').replace(/© 2025 ToolNest Studio\./g,'© 2026 ToolNest Studio.').replace(/(22|51|52|55)\+/g,'56+').replace(/support@toolneststudio\.com|privacy@toolneststudio\.com/gi,'toolneststudiosupport@gmail.com')}})}
  function schemaFix(){qsa('script[type="application/ld+json"]').forEach(function(s){try{var d=JSON.parse(s.textContent);if(d&&d['@type']==='Article'){d.author={'@type':'Organization',name:'ToolNest Studio Team'};d.publisher={'@type':'Organization',name:'ToolNest Studio'};s.textContent=JSON.stringify(d)}}catch(e){}})}
  function footerLinks(){var f=qs('footer .fg2')||qs('footer');if(!f||qs('.tn-policy-links',f))return;var d=document.createElement('div');d.className='tn-policy-links';d.innerHTML='<a href="'+rel('sitemap.xml')+'">Sitemap</a><a href="'+rel('sitemap-blog.xml')+'">Blog Sitemap</a><a href="'+rel('privacy-policy.html')+'">Privacy</a><a href="'+rel('editorial-policy.html')+'">Editorial Policy</a>';f.appendChild(d)}
  function toolGuide(){if(!isTool()||qs('.tn-guide'))return;var n=pageTitle();var sec=document.createElement('section');sec.className='tn-guide';sec.innerHTML='<div class="tn-guide-box"><div class="ey">Tool guide</div><h2>'+n+' guide</h2><p>'+n+' is a free ToolNest Studio browser tool created to help visitors complete a common task quickly without installing extra software. It supports students, bloggers, creators, developers, freelancers and small business owners who need fast, simple results.</p><div class="tn-guide-grid"><div class="tn-guide-card"><h3>What this tool does</h3><p>It takes your input, processes it in the browser, and gives a practical result you can review, copy, download, print or reuse depending on the page features.</p></div><div class="tn-guide-card"><h3>How to use it</h3><ol><li>Read the input labels.</li><li>Enter or paste the needed information.</li><li>Click the main action button.</li><li>Review the result carefully.</li></ol></div><div class="tn-guide-card"><h3>Real-world example</h3><p>A student can revise faster, a blogger can prepare publishing assets, a developer can test text or code, and a business owner can save time on routine work.</p></div><div class="tn-guide-card"><h3>FAQ</h3><p><strong>Is it free?</strong> Yes. <strong>Is an account needed?</strong> No. <strong>Should I verify results?</strong> Yes, review important outputs.</p></div></div></div>';var foot=qs('footer');if(foot)foot.parentNode.insertBefore(sec,foot);else document.body.appendChild(sec)}
  function init(){styles();textFixes();schemaFix();footerLinks();toolGuide()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
