(function(){
  var GA_ID='G-S7TGS7QSZW';
  var STORAGE={theme:'tn-theme',fav:'tn-favorites',recent:'tn-recent',rating:'tn-ratings'};
  function qs(s,r){return (r||document).querySelector(s)}
  function qsa(s,r){return [].slice.call((r||document).querySelectorAll(s))}
  function isToolPage(){return location.pathname.indexOf('/tools/')>-1}
  function rel(path){return isToolPage()?'../'+path:path}
  function parse(k,fb){try{return JSON.parse(localStorage.getItem(k))||fb}catch(e){return fb}}
  function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
  function title(){var h=qs('h1');return (h?h.textContent:document.title).replace(/\s+/g,' ').replace(/^[^A-Za-z0-9]+/,'').replace(/\s*\|\s*ToolNest Studio$/,'').trim()||'ToolNest Studio'}
  function url(){return location.pathname.replace(/^\//,'')||'index.html'}
  function toast(msg){var t=document.createElement('div');t.className='tn-toast';t.textContent=msg;document.body.appendChild(t);setTimeout(function(){t.remove()},1800)}
  function theme(v){document.documentElement.setAttribute('data-theme',v);try{localStorage.setItem(STORAGE.theme,v)}catch(e){}var b=qs('[data-tn-theme]');if(b)b.textContent=v==='light'?'🌙 Dark':'☀️ Light'}

  function analytics(){if(window.gtag||qs('script[src*="googletagmanager.com/gtag/js?id='+GA_ID+'"]'))return;window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments)};var s=document.createElement('script');s.async=true;s.src='https://www.googletagmanager.com/gtag/js?id='+GA_ID;document.head.appendChild(s);window.gtag('js',new Date());window.gtag('config',GA_ID)}
  function globalStyle(){if(qs('#tn-global-upgrades'))return;var st=document.createElement('style');st.id='tn-global-upgrades';st.textContent='.hamburger{display:none;background:var(--s);border:1px solid var(--b2);border-radius:10px;color:var(--t);font-size:1.15rem;padding:.42rem .68rem;line-height:1;box-shadow:0 8px 22px rgba(0,0,0,.16)}.cat-card strong,.tc-card strong{display:block;margin-bottom:.45rem}.cat-card p,.tc-card p{margin-top:.35rem}.tn-no-results{grid-column:1/-1;background:var(--s);border:1px dashed var(--b2);border-radius:var(--rx);padding:2rem;text-align:center;color:var(--t2);line-height:1.7}.tn-no-results strong{display:block;color:var(--t);font-size:1.05rem;margin-bottom:.35rem}.tn-usage-pill{display:inline-flex;align-items:center;gap:.45rem;background:rgba(245,158,11,.1);border:1px solid rgba(245,158,11,.26);border-radius:999px;color:#fcd34d;font-size:.72rem;font-weight:800;padding:.3rem .8rem;margin-left:.45rem;vertical-align:middle}@media(max-width:768px){.hamburger{display:inline-flex;align-items:center;justify-content:center}.nls{display:none!important;position:fixed;top:68px;left:.75rem;right:.75rem;background:rgba(3,7,18,.96);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);border:1px solid var(--b2);border-radius:18px;padding:.85rem;flex-direction:column;align-items:stretch;gap:.35rem;z-index:250;box-shadow:0 22px 50px rgba(0,0,0,.32)}.nls.open{display:flex!important}.nls li{width:100%}.nls a{width:100%;padding:.72rem .9rem}.nls .nc{text-align:center;margin-top:.25rem}.tn-usage-pill{display:flex;width:max-content;margin:.55rem 0 0}}html[data-theme="light"] .nls{background:rgba(248,250,252,.96)}';document.head.appendChild(st)}
  function mobileNav(){var nav=qs('#tnav')||qs('nav'),list=qs('.nls',nav);if(!nav||!list||qs('.hamburger',nav))return;var btn=document.createElement('button');btn.className='hamburger';btn.type='button';btn.setAttribute('aria-label','Open menu');btn.setAttribute('aria-expanded','false');btn.textContent='☰';nav.insertBefore(btn,list);btn.onclick=function(){var open=list.classList.toggle('open');btn.textContent=open?'✕':'☰';btn.setAttribute('aria-expanded',open?'true':'false')};list.addEventListener('click',function(e){if(e.target.tagName==='A'){list.classList.remove('open');btn.textContent='☰';btn.setAttribute('aria-expanded','false')}});document.addEventListener('click',function(e){if(!nav.contains(e.target)&&list.classList.contains('open')){list.classList.remove('open');btn.textContent='☰';btn.setAttribute('aria-expanded','false')}})}
  function announcement(){
    if(qs('.tn-announcement'))return;
    var st=document.createElement('style');
    st.textContent='.tn-announcement{position:relative;z-index:80;background:linear-gradient(135deg,rgba(6,182,212,.97),rgba(139,92,246,.97));color:#fff;border-bottom:1px solid rgba(255,255,255,.2);box-shadow:0 8px 22px rgba(0,0,0,.18)}.tn-announcement-inner{max-width:1320px;margin:0 auto;padding:.58rem 1.15rem;display:flex;align-items:center;justify-content:center;gap:.6rem;text-align:center;font-size:.82rem;font-weight:600;line-height:1.45}.tn-announcement a{color:#fff;text-decoration:underline;text-underline-offset:3px;font-weight:900}.tn-announcement-icon{flex:0 0 auto}@media(max-width:760px){.tn-announcement-inner{font-size:.74rem;padding:.55rem .8rem;align-items:flex-start}}@media print{.tn-announcement{display:none!important}}';
    document.head.appendChild(st);
    var bar=document.createElement('div');bar.className='tn-announcement';bar.setAttribute('role','status');bar.innerHTML='<div class="tn-announcement-inner"><span class="tn-announcement-icon">📢</span><span><strong>Announcement:</strong> ToolNest Studio is continuously improving. Our team regularly updates and upgrades the tools. If you have an idea to improve an existing tool or want to suggest a new tool, please share your full idea through the <a href="'+rel('contact.html')+'">Contact page</a>. We will review your suggestion and work on useful upgrades as soon as possible.</span></div>';
    var main=qs('main');
    if(main)main.insertBefore(bar,main.firstChild);else document.body.insertBefore(bar,document.body.firstChild);
  }
  function housekeeping(){
    document.documentElement.style.setProperty('--r-lg','22px');
    qsa('nav .nls').forEach(function(list){var links=qsa('a[href$="contact.html"]',list),cta=links.find(function(a){return a.classList.contains('nc')});if(cta)links.forEach(function(a){if(a!==cta&&a.textContent.trim().toLowerCase()==='contact'){var li=a.closest('li');if(li)li.remove()}})});
    qsa('.fbot span:first-child').forEach(function(el){if(/©\s*\d{4}\s*ToolNest Studio\./.test(el.textContent))el.textContent='© '+new Date().getFullYear()+' ToolNest Studio.'});
    qsa('.offline-badge').forEach(function(b){if(!/Live Rates/i.test(b.textContent)){b.textContent='Browser ✓';b.title='Runs locally in your browser where possible. Your input is not uploaded.'}});
    qsa('footer .fb p').forEach(function(p){if(/\d+\+ free AI browser tools/i.test(p.textContent)||/\d+\+ free browser tools/i.test(p.textContent))p.textContent='52+ free browser tools.'});
    var nav=qs('#tnav');if(nav)window.addEventListener('scroll',function(){nav.classList.toggle('sc',scrollY>40)},{passive:true});
  }
  function recent(){if(!isToolPage())return;var r=parse(STORAGE.recent,[]).filter(function(x){return x.url!==url()});r.unshift({title:title(),url:url(),at:Date.now()});save(STORAGE.recent,r.slice(0,5))}
  function socialProof(){if(!(location.pathname==='/'||/index\.html$/.test(location.pathname)))return;var target=qs('.rv div[style*="51+"]')||qs('.rv div[style*="52+"]');var hero=qs('section h1');if(!hero||qs('.tn-usage-pill'))return;var seed=new Date().toISOString().slice(0,10).split('').reduce(function(a,c){return a+c.charCodeAt(0)},0);var count=900+(seed%700);var pill=document.createElement('span');pill.className='tn-usage-pill';pill.textContent='🔥 '+count.toLocaleString()+' tools used today';hero.parentNode.insertBefore(pill,hero.nextSibling)}
  function homepageCurrency(){
    if(!(location.pathname==='/'||/index\.html$/.test(location.pathname)))return;
    qsa('body *').forEach(function(el){if(el.childElementCount===0&&el.textContent&&/51\+/.test(el.textContent))el.textContent=el.textContent.replace(/51\+/g,'52+')});
    if(qs('a[href="tools/currency-converter.html"]'))return;
    var grid=qs('#tool-grid');
    if(!grid)return;
    var html='<a class="tc-card rv on" href="tools/currency-converter.html" data-cat="finance" data-name="currency converter live exchange rates gbp usd byn lkr inr pkr finance students"><div class="card-emoji">💱</div><strong>Live Currency Converter</strong><p style="font-size:.78rem;color:var(--t2);line-height:1.5;margin:.45rem 0">Convert GBP, USD, BYN, LKR, INR and PKR using live exchange rates.</p><div class="card-meta"><span style="font-size:.7rem;color:var(--t3);text-transform:uppercase">finance</span><span class="offline-badge">Live Rates</span></div></a>';
    grid.insertAdjacentHTML('afterbegin',html);
  }
  function noResultsState(){var grid=qs('#tool-grid'),search=qs('#tool-search');if(!grid||!search)return;var box=qs('#tn-no-results');if(!box){box=document.createElement('div');box.id='tn-no-results';box.className='tn-no-results';box.hidden=true;box.innerHTML='<strong>No tools found</strong><span>Try a different keyword or choose another category.</span>';grid.appendChild(box)}function sync(){setTimeout(function(){var cards=qsa('.tc-card',grid),visible=cards.some(function(c){return !c.hidden});box.hidden=visible},30)}search.addEventListener('input',sync);qsa('.filter-btn').forEach(function(b){b.addEventListener('click',sync)});sync()}
  function breadcrumbSchema(){if(qs('script[data-tn-breadcrumb]'))return;var bc=qs('.bc');if(!bc)return;var items=[],pos=1;items.push({'@type':'ListItem',position:pos++,name:'Home',item:'https://toolneststudio.online/'});qsa('a,span',bc).forEach(function(el){var txt=el.textContent.trim();if(!txt||txt==='/'||txt.toLowerCase()==='home')return;if(el.tagName==='A')items.push({'@type':'ListItem',position:pos++,name:txt,item:new URL(el.getAttribute('href'),location.href).href});else items.push({'@type':'ListItem',position:pos++,name:txt})});if(items.length<2)return;var s=document.createElement('script');s.type='application/ld+json';s.setAttribute('data-tn-breadcrumb','1');s.textContent=JSON.stringify({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:items});document.head.appendChild(s)}
  function faqSchema(){if(qs('script[data-tn-faq]'))return;var details=qsa('details');if(!details.length)return;var main=details.slice(0,8).map(function(d){var q=qs('summary',d),p=qs('p',d);return q&&p?{'@type':'Question',name:q.textContent.trim(),acceptedAnswer:{'@type':'Answer',text:p.textContent.trim()}}:null}).filter(Boolean);if(!main.length)return;var s=document.createElement('script');s.type='application/ld+json';s.setAttribute('data-tn-faq','1');s.textContent=JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity:main});document.head.appendChild(s)}
  function seoBlocks(){
    if(!isToolPage()||qs('.tn-seo-block'))return;
    var p=location.pathname.split('/').pop();
    var d={
      'gpa-calculator.html':['GPA Calculator','Use this GPA calculator to add each course, choose the credits, pick the letter grade, mark weighted classes if needed, then calculate your semester GPA.','course credits, weighted GPA, target GPA, quality points and exportable reports','education-tools.html','Citation Generator,Study Schedule Builder,Flashcard Maker'],
      'citation-generator.html':['Citation Generator','Use this citation generator by choosing APA, MLA or Chicago, selecting the source type, entering author and publication details, then copying or exporting your citation.','APA citations, MLA citations, Chicago citations, website citations, book citations and saved bibliography items','education-tools.html','GPA Calculator,Quiz Generator,Study Schedule Builder'],
      'flashcard-maker.html':['Flashcard Maker','Use this flashcard maker to add a question and answer, study cards one by one, flip cards, shuffle your deck, import bulk cards, print or export your set.','study cards, local deck saving, shuffle mode, bulk import, CSV export and print support','education-tools.html','Quiz Generator,Study Schedule Builder,Mind Map Creator'],
      'quiz-generator.html':['Quiz Generator','Use this quiz generator to create multiple-choice questions, select correct answers, take the quiz, score responses and export or print the answer key.','multiple-choice quizzes, scoring, answer keys, bulk import, sample quizzes and CSV export','education-tools.html','Flashcard Maker,Citation Generator,GPA Calculator'],
      'study-schedule-builder.html':['Study Schedule Builder','Use this study schedule builder by entering your subjects, available hours, breaks, exam date and fixed tuition blocks to generate a weekly timetable.','subject rotation, exam countdown, busy blocks, study blocks, CSV export and printable plans','education-tools.html','GPA Calculator,Flashcard Maker,Mind Map Creator'],
      'sitemap-generator.html':['Sitemap Generator','Use this sitemap generator by entering your website URLs, choosing lastmod, change frequency and priority, then copying or downloading the XML sitemap.','XML sitemap output, URL validation, lastmod, changefreq, priority, copy and download support','seo-tools.html','Robots.txt Generator,Meta Tag Generator,UTM Link Builder'],
      'robots-txt-generator.html':['Robots.txt Generator','Use this robots.txt generator to define crawler rules, allow or block paths, add crawl delay and include your sitemap URL.','crawler rules, user-agent settings, allow/disallow paths, crawl delay and sitemap reference','seo-tools.html','Sitemap Generator,Meta Tag Generator,Keyword Density Checker'],
      'meta-tag-generator.html':['Meta Tag Generator','Use this meta tag generator to create title tags, descriptions, Open Graph tags, Twitter Card tags, canonical tags, robots rules and JSON-LD snippets.','SEO metadata, social previews, canonical URLs, robots tags, Open Graph, Twitter Cards and schema output','seo-tools.html','Keyword Density Checker,OG Image Previewer,Sitemap Generator'],
      'json-formatter.html':['JSON Formatter & Validator','Use this JSON formatter to paste JSON, format it, validate syntax, minify it, copy the result or download it for development work.','JSON formatting, validation, minification, error hints, copy and download support','developer-tools.html','Base64 Encoder / Decoder,URL Encoder / Decoder,Regex Tester'],
      'qr-code-generator.html':['QR Code Generator','Use this QR code generator by entering text, a URL or vCard details, then export the QR code as PNG or SVG.','text QR codes, URL QR codes, vCard mode, PNG export, SVG export and copy image support','productivity-tools.html','URL Encoder / Decoder,Bio Link Generator,UTM Link Builder'],
      'currency-converter.html':['Live Currency Converter','Use this currency converter by typing an amount in GBP, USD, BYN, LKR, INR or PKR. The other three currency boxes update instantly from the entered value.','four linked currency inputs, live exchange-rate fetching, browser cache, copy results and clear/reset support','finance-tools.html','Budget Calculator,Invoice Calculator,Tip Calculator']
    }[p];
    if(!d)return;var rels=d[4].split(',').map(function(x){return '<li>'+x+'</li>'}).join('');
    var html='<section class="tn-seo-block con rv on" style="padding:3rem 1.5rem 4rem"><div style="background:var(--s);border:1px solid var(--b);border-radius:var(--rx);padding:2rem"><div class="ey">Guide</div><h2 style="font-size:clamp(1.5rem,3vw,2.25rem);font-weight:800;letter-spacing:-.04em;margin:.4rem 0 1rem">How to use '+d[0]+'</h2><p style="color:var(--t2);line-height:1.75">'+d[1]+'</p><h3 style="margin-top:1.5rem">Key features</h3><p style="color:var(--t2);line-height:1.75">This free browser-powered tool includes '+d[2]+'. It is designed for fast everyday use without account setup.</p><h3 style="margin-top:1.5rem">Frequently asked questions</h3><details open><summary>Is '+d[0]+' free?</summary><p>Yes. '+d[0]+' is free to use on ToolNest Studio.</p></details><details><summary>Does this tool upload my data?</summary><p>Supported ToolNest tools run in your browser where possible. Check the privacy note on each tool page for details.</p></details><details><summary>Can I use this tool on mobile?</summary><p>Yes. ToolNest tools are designed to work on desktop and mobile browsers.</p></details><h3 style="margin-top:1.5rem">Related tools</h3><ul style="color:var(--t2);line-height:1.8">'+rels+'</ul><p><a class="btn bg" href="../'+d[3]+'">View category page</a></p></div></section>';
    var f=qs('footer');if(f)f.insertAdjacentHTML('beforebegin',html);
  }
  function quick(){
    if(qs('.tn-quick'))return;var div=document.createElement('div');div.className='tn-quick';div.innerHTML='<button type="button" data-tn-theme>☀️ Light</button>'+(isToolPage()?'<button type="button" data-tn-fav>☆ Favorite</button><button type="button" data-tn-share>↗ Share</button><button type="button" data-tn-up>👍</button><button type="button" data-tn-down>👎</button>':'');document.body.appendChild(div);theme(localStorage.getItem(STORAGE.theme)||'dark');qs('[data-tn-theme]',div).onclick=function(){theme((document.documentElement.getAttribute('data-theme')||'dark')==='dark'?'light':'dark')};
    if(!isToolPage())return;var cur={title:title(),url:url()},favs=parse(STORAGE.fav,[]),ratings=parse(STORAGE.rating,{}),fb=qs('[data-tn-fav]',div),up=qs('[data-tn-up]',div),down=qs('[data-tn-down]',div);function sync(){var on=favs.some(function(x){return x.url===cur.url});fb.textContent=on?'★ Favorited':'☆ Favorite';fb.classList.toggle('is-on',on);up.classList.toggle('is-on',ratings[cur.url]==='up');down.classList.toggle('is-on',ratings[cur.url]==='down')}fb.onclick=function(){var on=favs.some(function(x){return x.url===cur.url});favs=on?favs.filter(function(x){return x.url!==cur.url}):[cur].concat(favs).slice(0,12);save(STORAGE.fav,favs);sync();toast(on?'Removed from favorites':'Added to favorites')};qs('[data-tn-share]',div).onclick=function(){var u=location.href;if(navigator.share)navigator.share({title:title(),url:u}).catch(function(){});else if(navigator.clipboard){navigator.clipboard.writeText(u);toast('Tool link copied')}};up.onclick=function(){ratings[cur.url]=ratings[cur.url]==='up'?'':'up';save(STORAGE.rating,ratings);sync();toast('Thanks for the feedback')};down.onclick=function(){ratings[cur.url]=ratings[cur.url]==='down'?'':'down';save(STORAGE.rating,ratings);sync();toast('Thanks for the feedback')};sync();
  }
  function keys(){document.addEventListener('keydown',function(e){var run=qs('[data-run],#qr-generate,#json-format,#wc-run,#md-render,#pal-generate,#pomo-start,#cd-start,#name-generate,#tip-calc,#b64-run,#url-run,#hash-run,#rx-run,#cron-run,#jwt-run,#grad-run,#ent-run,#meta-run,#kw-run,#og-run,#utm-run,#robots-run,#sitemap-run,#fc-run,#quiz-run,#cite-run,#ss-run,#mm-run,#gpa-run,#cc-refresh'),clear=qs('[data-clear],#qr-clear,#json-clear,#wc-clear,#md-clear,#pal-reset,#pomo-reset,#cd-reset,#name-clear,#tip-clear,#b64-clear,#url-clear,#hash-clear,#rx-clear,#cron-clear,#jwt-clear,#grad-clear,#ent-clear,#meta-clear,#kw-clear,#og-clear,#utm-clear,#robots-clear,#sitemap-clear,#fc-clear,#quiz-clear,#cite-clear,#ss-clear,#mm-clear,#gpa-clear,#cc-clear');if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&run){e.preventDefault();run.click()}if(e.key==='Escape'&&clear)clear.click()})}
  function reveal(){if(window.matchMedia('(prefers-reduced-motion:reduce)').matches){qsa('.rv').forEach(function(el){el.classList.add('on')});return}var o=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add('on');o.unobserve(e.target)}})},{threshold:.07,rootMargin:'0px 0px -28px 0px'});qsa('.rv').forEach(function(el){o.observe(el)})}
  function init(){analytics();globalStyle();theme(localStorage.getItem(STORAGE.theme)||'dark');mobileNav();announcement();housekeeping();recent();homepageCurrency();socialProof();seoBlocks();noResultsState();breadcrumbSchema();faqSchema();quick();keys();reveal()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();