document.addEventListener('DOMContentLoaded',function(){
  if(location.pathname.indexOf('/tools/')===-1)return;
  if(document.querySelector('.tn-tool-guide'))return;
  var h=document.querySelector('h1');
  var name=(h?h.textContent:document.title).replace(/\s+/g,' ').replace(/^[^A-Za-z0-9]+/,'').replace(/\s*\|\s*ToolNest Studio$/,'').trim()||'This tool';
  var style=document.createElement('style');
  style.textContent='.tn-tool-guide{max-width:1120px;margin:0 auto 4rem;padding:0 1.5rem}.tn-tool-guide-box{background:var(--s);border:1px solid var(--b);border-radius:24px;padding:1.8rem}.tn-tool-guide h2{font-size:clamp(1.35rem,3vw,2rem);margin:0 0 .75rem}.tn-tool-guide h3{font-size:1rem;margin:1rem 0 .35rem}.tn-tool-guide p,.tn-tool-guide li{color:var(--t2);line-height:1.75;font-size:.92rem}.tn-tool-guide-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:1rem;margin-top:1rem}.tn-tool-guide-card{border:1px solid var(--b);border-radius:18px;padding:1rem;background:rgba(255,255,255,.03)}';
  document.head.appendChild(style);
  var sec=document.createElement('section');
  sec.className='tn-tool-guide rv';
  sec.innerHTML='<div class="tn-tool-guide-box"><div class="ey">Tool guide</div><h2>'+name+' guide</h2><p>'+name+' is a free browser-based ToolNest Studio utility created to help users complete a specific online task faster. Instead of installing extra software or switching between many websites, you can open this page, enter the required information, and review the result directly in your browser. The tool is useful for students, creators, bloggers, developers, freelancers, and small business users who need quick help with everyday digital work.</p><div class="tn-tool-guide-grid"><div class="tn-tool-guide-card"><h3>Step-by-step instructions</h3><ol><li>Read the input labels carefully.</li><li>Enter or paste the required information.</li><li>Use the main button to calculate, format, generate, check, or preview.</li><li>Review the result for mistakes or missing details.</li><li>Copy, download, print, or reuse the output if the page provides that option.</li></ol></div><div class="tn-tool-guide-card"><h3>Real-world example</h3><p>A student may use this tool while preparing assignments or revision material. A blogger may use it before publishing content. A developer may use it while testing data or formatting code. A small business owner may use it to save time on simple daily tasks.</p></div><div class="tn-tool-guide-card"><h3>FAQ</h3><details open><summary>Is this tool free?</summary><p>Yes. It is free to use on ToolNest Studio.</p></details><details><summary>Do I need an account?</summary><p>No account is required. Open the page and start using the tool.</p></details><details><summary>Should I verify the result?</summary><p>Yes. Always review important outputs before using them for school, business, finance, code, or publishing work.</p></details></div></div></div>';
  var footer=document.querySelector('footer');
  if(footer)footer.parentNode.insertBefore(sec,footer);else document.body.appendChild(sec);
});
